## YAML Template.
---
parameters:
    crudforge_generate_crud.class: Crudforge\CrudforgeBundle\CrudforgeCore\GenerateCrud
    crudforge_security.class: Crudforge\CrudforgeBundle\CrudforgeCore\CrudforgeSecurity

services:
    crudforge.core:
        class:        "%crudforge_generate_crud.class%"
        arguments: ['@service_container']
    crudforge.security:
        class:        "%crudforge_security.class%"
        arguments: ['@service_container']
    crudforge.type.entity_hidden:
      class: Crudforge\CrudforgeBundle\Form\Type\EntityHiddenType
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
      - { name: form.type, alias: entity_hidden }
